import { FaAngleRight } from "react-icons/fa6";

const Jobs = () => {
  return (
    <div className="w-[100%] flex flex-col">
      <div>
        <div className="w-full m-auto">
          <div className="bg-[url('/bg.png')] bg-cover w-[100%] lg:flex-row flex flex-col items-center justify-center py-[80px] max-md:py-[30px] px-[80px] max-tab:px-[40px] max-laptop:px-[80px] max-md:px-[30px] gap-[4%] ">
            <div className="max-w-[2000px] w-full mx-auto flex gap-[60px] justify-between   items-center px-[40px]  max-lg:p-[40px] max-md:p-[0px]">
              <div className="w-full  text-white flex flex-col gap-6 ">
                <h3 className="text-sm font-[Outfit-Bold] max-laptop:text-mf max-md:text-center">
                  Join Us
                </h3>
                <h1 className="font-[Outfit-Bold] text-left text-lg font-black leading-[60px] max-laptop:text-lf max-md:text-sm max-md:leading-8 max-md:text-center max-laptop:font-[700] max-laptop:leading-10">
                  Werde ein Teil von FAST Al Movies!
                </h1>
                <p className="font-[Outfit-Regular] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                  FAST AI Movies is a highly innovative AI start-up that
                  generates training videos for medium-sized companies
                  automatically with the help of AI. The customer only provides
                  FAST AI Movies with a short input script and everything else
                  is generated by the AI Software. We empower our team to own
                  their projects end to end and actively contribute throughout
                  the product life cycle. To accelerate your growth path, you
                  will work in a highly innovative tech start-up directly with
                  the NLP lead and the founder.
                </p>
                <div className="btn flex gap-[20px] max-md:flex-col">
                  <button className="font-[Outfit-Bold] text-primary text-sm font-bold bg-white px-4 py-3 rounded-[12px] whitespace-nowrap max-laptop:text-mf">
                    Jetzt bewerben!
                  </button>
                </div>
              </div>
              <div className=" w-full lg:flex hidden">
                <video className=" object-cover m-auto   controls autoPlay muted">
                  <source
                    className="w-full h-full object-cover"
                    src="./flexvid/vid.mp4"
                    type="video/mp4"
                  />
                </video>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="max-w-[2000px] mx-auto  w-[100%] flex flex-col lg:px-[80px] px-[20px] pt-[50px]">
        <div className="w-[100%] flex items-center lg:gap-6 md:gap-4 gap-3 flex-col lg:mt-[50px] md:mt-[30px] mt-[20px]">
          <div className="w-[93%] lg:h-[140px] md:h-[80px] h-60px bg-light100  rounded-[5px] flex lg:px-[50px] md:px-[20px] px-[10px] py-[10px] justify-between shadow-md  items-center">
            <div>
              <div className="font-[Outfit-Bold] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                Project Study in Business Development
              </div>
              <div className="font-[Outfit-Regular] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                (Complaince/legal market segment)
              </div>
            </div>
            <div className="text-[40px]   text-light200">
              <FaAngleRight />
            </div>
          </div>

          <div className="w-[93%] lg:h-[140px] md:h-[80px] h-60px bg-light100  rounded-[5px] flex lg:px-[50px] md:px-[20px] px-[10px] py-[10px] justify-between shadow-md  items-center">
            <div>
              <div className="font-[Outfit-Bold] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start ">
                Project Study in Business Development
              </div>
              <div className="font-[Outfit-Regular] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                (Complaince/legal market segment)
              </div>
            </div>
            <div className="text-[40px]   text-light200">
              <FaAngleRight />
            </div>
          </div>

          <div className="w-[93%] lg:h-[140px] md:h-[80px] h-60px bg-light100  rounded-[5px] flex lg:px-[50px] md:px-[20px] px-[10px] py-[10px] justify-between shadow-md  items-center">
            <div>
              <div className="font-[Outfit-Bold] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start ">
                Project Study in Business Development
              </div>
              <div className="font-[Outfit-Regular] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                (Complaince/legal market segment)
              </div>
            </div>
            <div className="text-[40px] text-light200">
              <FaAngleRight />
            </div>
          </div>

          <div className="w-[93%] lg:h-[140px] md:h-[80px] h-60px bg-light100  rounded-[5px] flex lg:px-[50px] md:px-[20px] px-[10px] py-[10px] justify-between shadow-md  items-center">
            <div>
              <div className="font-[Outfit-Bold] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                Project Study in Business Development
              </div>
              <div className="font-[Outfit-Regular] text-left text-sm  max-tab:w-auto max-md:text-mf max-laptop:text-mf max-md:text-start">
                (Complaince/legal market segment)
              </div>
            </div>
            <div className="text-[40px] font-[900] text-light200">
              <FaAngleRight />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Jobs;
